amazon:
   service: S3
   access_key_id: <%= Rails.application.credentials.dig(:aws, :ACCESS_KEY) %>
   secret_access_key: <%= Rails.application.credentials.dig(:aws, :SECRET_ACCESS_KEY) %>
   region: us-east-1
   bucket: kindergartenapp